version: '3.8'
services:
  app:
    build: .
    container_name: rag_telegram_bot
    env_file:
      - env.example
    volumes:
      - ./chroma_db:/app/chroma_db
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:7.2-alpine
    container_name: rag_redis
    restart: unless-stopped
    ports:
      - "6379:6379" 